2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_setup.py:_flush():81] Configure stats pid to 665986
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_setup.py:_flush():81] Loading settings from /home/bzhao/.config/wandb/settings
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_setup.py:_flush():81] Loading settings from /home/bzhao/Deep-Learning/Assignment2/wandb/settings
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_init.py:setup_run_log_directory():705] Logging user logs to outputs/logs/wandb/run-20251027_170032-era4cyzx/logs/debug.log
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to outputs/logs/wandb/run-20251027_170032-era4cyzx/logs/debug-internal.log
2025-10-27 17:00:32,850 INFO    MainThread:665986 [wandb_init.py:init():832] calling init triggers
2025-10-27 17:00:32,851 INFO    MainThread:665986 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-27 17:00:32,851 INFO    MainThread:665986 [wandb_init.py:init():880] starting backend
2025-10-27 17:00:33,055 INFO    MainThread:665986 [wandb_init.py:init():883] sending inform_init request
2025-10-27 17:00:33,058 INFO    MainThread:665986 [wandb_init.py:init():891] backend started and connected
2025-10-27 17:00:33,059 INFO    MainThread:665986 [wandb_init.py:init():961] updated telemetry
2025-10-27 17:00:33,062 INFO    MainThread:665986 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-27 17:00:33,795 INFO    MainThread:665986 [wandb_init.py:init():1036] starting run threads in backend
2025-10-27 17:00:33,836 INFO    MainThread:665986 [wandb_run.py:_console_start():2509] atexit reg
2025-10-27 17:00:33,836 INFO    MainThread:665986 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-27 17:00:33,836 INFO    MainThread:665986 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-27 17:00:33,836 INFO    MainThread:665986 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-27 17:00:33,837 INFO    MainThread:665986 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-27 17:00:33,982 INFO    MainThread:665986 [wandb_run.py:_config_callback():1392] config_cb None None {'in_channels': 3, 'num_classes': 3, 'base_channels': 32, 'depth': 6, 'deep_supervision': False, 'lr': 0.001, 'weight_decay': 0.0001, 'max_epochs': 150, 'use_dice_loss': True, 'use_tta': False}
2025-10-27 17:02:22,225 INFO    wandb-AsyncioManager-main:665986 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-27 17:02:22,225 INFO    wandb-AsyncioManager-main:665986 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-10-27 17:02:22,232 ERROR   MainThread:665986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2436, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/miniforge3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniforge3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/opt/miniforge3/lib/python3.12/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/opt/miniforge3/lib/python3.12/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2025-10-27 17:02:22,236 ERROR   MainThread:665986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2436, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/miniforge3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniforge3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/home/bzhao/Deep-Learning/Assignment2/.venv/lib/python3.12/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/opt/miniforge3/lib/python3.12/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/opt/miniforge3/lib/python3.12/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
